services:
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    volumes:
      - mysql-data:/var/lib/mysql

  fastapi-app:
    build: ${DOCKER_USER}/python-app:latest
    environment:
      DB_HOST: mysql-db
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASS}
      DB_NAME: ${MYSQL_DB}
    ports:
      - "8000:8000"
    depends_on:
      - mysql-db

volumes:
  mysql-data:
