services:
  mysql-db:
    image: mysql:8.0
    env:
      parameter-store:
        MYSQL_PASS: /fastapi_app/mysqlpasswd
        MYSQL_USER: /fastapi_app/nysqluser
        MYSQL_DB: /fastapi_app/mysqldb
        DOCKER_USER: /fastapi_app/dockeruser
        DOCKER_PASS: /fastapi_app/docker_passwd
    volumes:
      - mysql-data:/var/lib/mysql

  fastapi-app:
    image: ${DOCKER_USER}/fastapi-app:latest
    environment:
      DB_HOST: mysql-db
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASS}
      DB_NAME: ${MYSQL_DB}
    ports:
      - "8000:8000"
    depends_on:
      - mysql-db

volumes:
  mysql-data:
